application: teamzero
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
#Static Handler:
- url: /static
  static_dir: static

- url: /newitem
  script: main.app
  login: required
  auth_fail_action: unauthorized
  
- url: /success
  script: main.app
  login: required
  auth_fail_action: unauthorized
  
- url: /userprofile
  script: main.app
  login: required
  auth_fail_action: unauthorized
  
- url: .*
  script: main.app
  

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest
